debug: &debug Yes
static_url: &static_url "http://localhost:9000/"
ipython_port: 8000

paths:
    root: &root !root
    client: &client !join [*root, client/]
    build: &build !join [*root, build/]
    vendor: &vendor !join [*root, gulp/vendor/]
    index: &index !join [*build, test/index.html]
    static: *root

server:
    root: *root
    livereload: true
    port: 9000

vendor_scripts: &vendor_scripts !prepend
    - *vendor
    - angular/angular.js
    - angular-ui-router/release/angular-ui-router.js
    - lodash/lodash.js
    - angular-bootstrap/ui-bootstrap-tpls.js
    - codemirror/lib/codemirror.js
    - codemirror/mode/python/python.js
    - angular-ui-codemirror/ui-codemirror.js

templates_dest: &templates_dest !join [*build, test/templates.js]

client_scripts: &client_scripts
    - !join [*client, "**/!(*.spec)*.js"]
    - *templates_dest

client_js: &client_js
    - !join [*client, "**/*.js"]

css_dest: &css_dest !join [*build, test/styles.css]

lint:
    src: *client_js
    watch: *client_js

html:
    src: !join [*client, test/index.html]
    dest: *index
    static_url: *static_url
    main: test
    includes: !flatten
        - *vendor_scripts
        - *client_scripts
        - !join [*vendor, codemirror/lib/codemirror.css]
        - *css_dest
    watch: !flatten
        - *client_scripts
        - !join [*client, test/index.html]

less:
    src: !join [*client, base.less]
    dest: *css_dest
    includes:
        - !join [*vendor, bootstrap/less/bootstrap.less]
        - !join [*client, "**/*.less"]
        - !join ["!", *client, base.less]
    vars:
        static_url: *static_url
        icon-font-path: !join [*static_url, gulp/vendor/bootstrap/fonts/]
    paths:
        - !join [*vendor, bootstrap/less]
    watch: !join [*client, "**/*.less"]

templates:
    standalone: true
    module: templates
    src: !join [*client, "**/*.tpl.html"]
    dest: *templates_dest
    watch: !join [*client, "**/*.tpl.html"]

karma:
    browsers:
        - Chrome
    frameworks:
        - jasmine
    reporters:
        - dots
    reportSlowerThan: 100
    files: !flatten
        - *vendor_scripts
        - !join [*vendor, angular-mocks/angular-mocks.js]
        - *client_js