debug: &debug Yes
https: No
static_url: &static_url "/"
port: 9000
port2: 8000

paths:
    root: &root '../' 
    client: &client !join [*root, client/]
    build: &build !join [*root, build/]
    static: *build
    vendor: &vendor !join [*root, gulp/vendor/]
    index: !join [*build, ipyng/index.html]

lint:
    - !join [*client, "**/*.js"]

karma:
    browsers:
        - Chrome
    frameworks:
        - jasmine
    reporters:
        - dots

apps:
    ipyng:
        less:
            watch:
                - !join [*client, ipyng/**/*.less]
                - !join [*client, base.less]
            template: !join [*client, base.less]
            vars:
                static_url: *static_url
                icon-font-path: !join [*static_url, fonts/]
            globs:
                - !join [*client, "ipyng/**/*.less"]
            includes:
                - bootstrap.less
            paths:
                - !join [*vendor, bootstrap/less]
            dest: !join [*build, ipyng/styles.css]

        html:
            scripts: &scripts !flatten
                - !prepend
                    - !join [*vendor, "@()"]
                    - angular/angular.js
                    - lodash/dist/lodash.js
                    - angular-ui-router/release/angular-ui-router.js
                    - angular-bootstrap/ui-bootstrap-tpls.js
                - !join [*client, "@()ng-lodash/ng-lodash.js"]
                - !join [*client, "@()ipyng/**/*.js"]
                - !join ["!", *client, "**/*.spec.js"]
            watch: !flatten
                - !join [*client, base.html]
                - !join [*client, ipyng/index.html]
                - *scripts
            template: !join [*client, ipyng/index.html]
            static_url: *static_url
            includes:
                - ipyng/ipyng.tpl.js
                - ipyng/styles.css
            dest: !join [*build, ipyng/index.html]
        karma:
            files:
                - !join [*build, angular/angular.js]
                - !join [*build, "**/*.js"]
                - !join [*vendor, angular-mocks/angular-mocks.js]
                - !join [*client, "ipyng/**/*.spec.js"]
        tpl:
            src:
                - !join [*client, ipyng/**/*.tpl.html]
            dest: !join [*build, ipyng/ipyng.tpl.js]

        copy:
            src:
                - !join [*vendor, bootstrap/fonts/*.*]
            dest:
                - !join [*build, fonts/]

    test:
        html:
            scripts: &scripts2 !flatten
                - !prepend
                    - !join [*vendor, "@()"]
                    - angular/angular.js
                    - lodash/dist/lodash.js
                - !join [*client, "@()ng-lodash/ng-lodash.js"]
                - !join [*client, "**/*.js"]
                - !join ["!", *client, "**/*.spec.js"]
            watch: !flatten
                - !join [*client, test/index.html]
                - !join [*client, base.html]
                - *scripts2
            template: !join [*client, test/index.html]
            static_url: "/"
            includes:
                - test/styles.css
                - ipyng/ipyng.tpl.js
            dest: !join [*build, test/index.html]
        less:
            watch:
                - !join [*client, ipyng/**/*.less]
                - !join [*client, base.less]
            template: !join [*client, base.less]
            vars:
                static_url: *static_url
                icon-font-path: !join [*static_url, fonts/]
            globs:
                - !join [*client, "ipyng/**/*.less"]
            includes:
                - bootstrap.less
            paths:
                - !join [*vendor, bootstrap/less]
            dest: !join [*build, test/styles.css]
